# Generated by Django 3.0 on 2020-07-29 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0004_auto_20200722_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=264, unique=True),
        ),
    ]
